# Generated by Django 5.2 on 2025-05-12 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeehouse', '0002_rename_item_price_order_cart_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('guests', models.IntegerField()),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='coffeehouse.order'),
        ),
    ]
